# Generated by Django 5.1 on 2024-08-26 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('titulo', '0002_alter_titulo_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Id do Instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do Instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do Instrutor', max_length=70)),
                ('dataNascimento', models.DateField(help_text='Informe a data de nascimento do T[itulo')),
                ('ddd', models.CharField(help_text='Informe o DDD do telefone do T[itulo', max_length=3)),
                ('telefone', models.CharField(help_text='Informe o telefone do T[itulo', max_length=9)),
                ('titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo')),
            ],
        ),
    ]
