# Generated by Django 5.1 on 2024-08-26 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
        ('titulo', '0002_alter_titulo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulo.titulo'),
        ),
    ]
