# Generated by Django 5.1 on 2024-08-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoatividade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoatividade',
            name='codigo',
            field=models.AutoField(help_text='Código do Tipo de atividade', primary_key=True, serialize=False),
        ),
    ]
