# Generated by Django 5.0.8 on 2024-08-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoatividade', '0002_tipoatividade_nome_alter_tipoatividade_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatividade',
            name='nome',
        ),
    ]
