# Generated by Django 5.0.8 on 2024-08-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipoatividade', '0004_tipoatividade_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoatividade',
            name='nome',
        ),
    ]
