# Generated by Django 5.0.8 on 2024-08-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Informe a matrícula do Aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do Aluno', max_length=70)),
                ('dataInicial', models.DateField(help_text='Informe a data de início de matrícula do Aluno')),
                ('dataFinal', models.DateField(blank=True, help_text='Informe a data de fim de matrícula do Aluno', null=True)),
            ],
        ),
    ]
