# Generated by Django 5.0.8 on 2024-08-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='dataFinal',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='aluno',
            old_name='dataInicial',
            new_name='data_inicial',
        ),
    ]
