# Generated by Django 5.1 on 2024-08-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('codigo', models.IntegerField(help_text='Código do Tipo do Título', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do T[itulo', max_length=70)),
            ],
        ),
    ]
