# Generated by Django 5.0.8 on 2024-08-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='codigo',
            field=models.AutoField(help_text='Código do Título', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(help_text='Informe a descrição do Título', max_length=70),
        ),
    ]
